### ISSUE TITLE
Links to LinkedIn returns constant http status codes of 999

### ISSUE THREAD

**Issue by magebarf** [marcobeierer/joomla-linkchecker#1]
Hi!

We have link in our header to our company page, and on every page we get a error 999 returned when performing the site check for broken links, every page pointing out an issue with the LinkedIn link.

I do see that this is not all too uncommon error, as there is already at least two StackOverflow page on the topic. The one most to the point with regards to potential fixes would be this one: https://stackoverflow.com/questions/27571419/how-to-avoid-http-1-1-999-request-denied-response-from-linkedin

As it still seems to hinge on not doing too many requests during a specific time interval from the same host, maybe it also needs to be coupled with a bit of caching on the server side, so the existence of a given LinkedIn page does not need to be verified for every time it is requested (which may already be in place, I'm unsure).

**Comment by marcobeierer** [comment]
Hi @magebarf 

Thank you for your report.

I'm aware of this problem but sadly caching does not help. The Link Checker already caches the requests and does just one request for each page every time it is used.

Linkedin does block all requests from "bots", independently of the number of requests.

The only way I see to fix this, is to simulate an browser when accessing LinkedIn, thus handle cookies, etc. Such a feature will come in the future, but I'm not sure if I could provide it in the free version as it requires much more resources than the current solution.

A simpler workaround would be to implement a function to hide broken links in the results view. Thus that you could mark one of your Linkedin links and it would not show as broken link on any page. So the results view would be much cleaner.

Best regards
Marco

**Comment by magebarf** [comment]
Hi @marcobeierer!

Yep, the workaround sounds like a good approach, as right now I'm guessing a lot of the users are quite confused why their LinkedIn page doesn't exist. :)

I do see a few options here, with the simplest one being to just add a small note under the "Custom status codes" mentioning that LinkedIn uses this for a specific case.

Second one, as you say, an option to hide links. I would guess on a per-link basis.

The third one I'm thinking about, which you probably have better insight than me if it's reasonable (depending on whether you see similar behavior for other web sites/servers as well or if it only is LinkedIn doing this); Add a "brown list", where any links on a domain on the list requires manual verification and then 👍 or 👎 to report the result which then can be cached server side for something like a week?

I think you have good ideas on where to take it, so I'm not worried where this goes. For other users I'm hoping just having this discussion enlightens them a bit, which in itself makes the reason for the issue more apparent.

**Comment by marcobeierer** [comment]
Hi @magebarf 

Sorry for my late reply. I forgot to reply back in November and have not worked much on the Link Checker lately.

Since two or three weeks I'm working again at the Link Checker and crawler and found a bug in the crawler. The crawler did not check the robots.txt file for external URLs. I fixed this and now the crawler does no longer run into the odd status code 999 errors and knows which URLs he is not allowed to access.

I will now add a new section to the Link Checker results where all links the crawler was blocked from are listed and also implement your suggestion to manually verify the links and mark them appropriately.

I'm also planning to implement support for Headless Chrome in the crawler. Headless Chrome should be able to access all pages a normal visitor could access. However this is not a main priority at the moment as there is still enough work to do.

By the way, if you like a free token for the Link Checker, just send me an email with the URL of your website.

Best regards
Marco

**Comment by marcobeierer** [comment]
everything is implemented now
